# https://docs.docker.com/compose/compose-file/
# https://github.com/compose-spec/compose-spec/blob/master/spec.md#services-top-level-element

version: '3.6'

networks:
  uwsapp: {}

services:

  uwsapi:
    image: uwsapp/devel
    container_name: uwsapi-devel
    hostname: uwsapi
    user: uws
    volumes:
      - ../../:/opt/uwsapp
      - ../../tmp:/opt/uwsapp/tmp
      - ../../data:/var/opt/uwsapp
    entrypoint: /opt/uwsapp/_devel/run.sh api
    environment:
      - UWSAPP_PORT=5100
      - UWSAPP_URL=api/
    read_only: true
    restart: "no"
    ports:
      - "127.0.0.1:5100:5100"
    networks:
      - uwsapp

  uwsweb:
    image: uwsapp/devel
    container_name: uwsweb-devel
    hostname: uwsweb
    user: uws
    volumes:
      - ../../:/opt/uwsapp
      - ../../tmp:/opt/uwsapp/tmp
      - ../../data:/var/opt/uwsapp
    entrypoint: /opt/uwsapp/_devel/run.sh web
    environment:
      - UWSAPP_PORT=5000
      - UWSAPP_URL=web/
    read_only: true
    restart: "no"
    ports:
      - "127.0.0.1:5000:5000"
    networks:
      - uwsapp
    depends_on:
      - uwsapi

  nginx:
    image: uwsapp/nginx
    container_name: uwsapp-nginx
    hostname: nginx
    user: root
    volumes:
      - ../../tmp:/opt/uwsapp/tmp
      - ../../data:/var/opt/uwsapp
      - type: tmpfs
        target: /var/log/nginx
      - type: tmpfs
        target: /var/tmp/nginx
      - type: tmpfs
        target: /var/lib/nginx
      - type: tmpfs
        target: /run
    read_only: true
    restart: "no"
    ports:
      - "127.0.0.1:8443:443"
    networks:
      - uwsapp
    depends_on:
      - uwsapi
      - uwsweb
