# https://docs.docker.com/compose/compose-file/
# https://github.com/compose-spec/compose-spec/blob/master/spec.md#services-top-level-element

version: '3.6'

networks:
  uwsapp: {}

services:

  uwsapi:
    image: uwsapp/devel
    container_name: uwsapi-devel
    hostname: uwsapi
    user: uws
    volumes:
      - ../../:/opt/uwsapp
      - ../../tmp:/opt/uwsapp/tmp
      - ../../data:/var/opt/uwsapp
      - ../../run:/run/uwsapp
      - ./run/uwscli:/run/uwscli:ro
    entrypoint: /opt/uwsapp/_devel/run.sh api
    environment:
      - UWSAPP_PORT=5100
      - UWSAPP_URL=api/
      - UWSAPP_HOST=localhost,nginx
    read_only: true
    restart: "no"
    ports:
      - "127.0.0.1:5100:5100"
    networks:
      - uwsapp

  uwsweb:
    image: uwsapp/devel
    container_name: uwsweb-devel
    hostname: uwsweb
    user: uws
    volumes:
      - ../../:/opt/uwsapp
      - ../../tmp:/opt/uwsapp/tmp
      - ../../data:/var/opt/uwsapp
      - ../../run/uwsapp:/run/uwsapp
      - ./run/uwscli:/run/uwscli:ro
    entrypoint: /opt/uwsapp/_devel/run.sh web
    environment:
      - UWSAPP_PORT=5000
      - UWSAPP_URL=web/
      - UWSAPP_API_HOST=nginx
      - UWSAPP_API_PORT=443
      - UWSAPP_API_TIMEOUT=5
      - UWSAPP_API_CERTFILE=/opt/uwsapp/tmp/devel-local.pem
      - UWSAPP_API_KEYFILE=/opt/uwsapp/tmp/devel-local-key.pem
      - UWSAPP_API_KEYPASS=/run/uwsapp/api_keypass
    read_only: true
    restart: "no"
    ports:
      - "127.0.0.1:5000:5000"
    networks:
      - uwsapp
    depends_on:
      - uwsapi

  uwshelp:
    image: uwsapp/devel
    container_name: uwshelp-devel
    hostname: uwshelp
    user: uws
    volumes:
      - ../../:/opt/uwsapp
      - ../../tmp:/opt/uwsapp/tmp
      - ../../data:/var/opt/uwsapp
      - ../../run:/run/uwsapp
    entrypoint: /opt/uwsapp/_devel/run.sh help
    environment:
      - UWSAPP_PORT=5001
      - UWSAPP_URL=help/
    read_only: true
    restart: "no"
    ports:
      - "127.0.0.1:5001:5001"
    networks:
      - uwsapp

  nginx:
    image: uwsapp/nginx
    container_name: uwsapp-nginx
    hostname: nginx
    user: root
    volumes:
      - ../../tmp:/opt/uwsapp/tmp
      - type: tmpfs
        target: /var/log/nginx
      - type: tmpfs
        target: /var/tmp/nginx
      - type: tmpfs
        target: /var/lib/nginx
      - type: tmpfs
        target: /run
    read_only: true
    restart: "no"
    ports:
      - "127.0.0.1:8443:443"
    networks:
      - uwsapp
    depends_on:
      - uwsapi
      - uwsweb
