# https://docs.docker.com/compose/compose-file/
# https://github.com/compose-spec/compose-spec/blob/master/spec.md#services-top-level-element

version: '3.6'

networks:
  uwsapp-${UWSAPP_ENV}: {}

services:

  uwsapi:
    image: 789470191893.dkr.ecr.us-west-1.amazonaws.com/uws:uwsapi-${UWSAPP_VERSION}
    container_name: uwsapi-${UWSAPP_ENV}-${UWSAPP_VERSION}
    hostname: uwsapi-${UWSAPP_ENV}
    volumes:
      - /srv/uwsapp/${UWSAPP_ENV}/data/api:/var/opt/uwsapp
      - /srv/uwsapp/${UWSAPP_ENV}/run/uwsapp:/run/uwsapp
      - /srv/uwscli/${UWSAPP_ENV}/run/auth:/run/uwscli/auth:ro
    environment:
      - UWSAPP_HOST=${UWSAPP_HOST}
      - UWSAPP_PORT=${UWSAPP_API_PORT}
    read_only: true
    restart: on-failure
    ports:
      - "127.0.0.1:${UWSAPP_API_PORT}:${UWSAPP_API_PORT}"
    networks:
      - uwsapp-${UWSAPP_ENV}

  uwsweb:
    image: 789470191893.dkr.ecr.us-west-1.amazonaws.com/uws:uwsweb-${UWSAPP_VERSION}
    container_name: uwsweb-${UWSAPP_ENV}-${UWSAPP_VERSION}
    hostname: uwsweb-${UWSAPP_ENV}
    volumes:
      - /srv/uwsapp/${UWSAPP_ENV}/data/web:/var/opt/uwsapp
    environment:
      - UWSAPP_HOST=${UWSAPP_HOST}
      - UWSAPP_PORT=${UWSAPP_WEB_PORT}
    read_only: true
    restart: on-failure
    ports:
      - "127.0.0.1:${UWSAPP_WEB_PORT}:${UWSAPP_WEB_PORT}"
    networks:
      - uwsapp-${UWSAPP_ENV}
    depends_on:
      - uwsapi

  uwshelp:
    image: 789470191893.dkr.ecr.us-west-1.amazonaws.com/uws:uwshelp-${UWSAPP_VERSION}
    container_name: uwshelp-${UWSAPP_ENV}-${UWSAPP_VERSION}
    hostname: uwshelp-${UWSAPP_ENV}
    volumes:
      - /srv/uwsapp/${UWSAPP_ENV}/data/help:/var/opt/uwsapp
    environment:
      - UWSAPP_HOST=${UWSAPP_HOST}
      - UWSAPP_PORT=${UWSAPP_HELP_PORT}
    read_only: true
    restart: on-failure
    ports:
      - "127.0.0.1:${UWSAPP_HELP_PORT}:${UWSAPP_HELP_PORT}"
    networks:
      - uwsapp-${UWSAPP_ENV}
