# https://docs.docker.com/compose/compose-file/
# https://github.com/compose-spec/compose-spec/blob/master/spec.md#services-top-level-element

version: '3.6'

networks:
  uwsapp-${UWSAPP_ENV}: {}

services:

  uwsapi:
    image: 789470191893.dkr.ecr.us-west-1.amazonaws.com/uws:uwsapi-${UWSAPP_VERSION}
    container_name: uwsapi-${UWSAPP_ENV}-${UWSAPP_VERSION}
    hostname: uwsapi-${UWSAPP_ENV}
    volumes:
      - /srv/uwsapp/${UWSAPP_ENV}/data/api:/var/opt/uwsapp
      - /srv/uwsapp/${UWSAPP_ENV}/run/uwsapi:/run/uwsapi
      - /srv/uwscli/${UWSAPP_ENV}/logs:/run/uwscli/logs:ro
      - /srv/uwscli/${UWSAPP_ENV}/run/auth:/run/uwscli/auth:ro
    environment:
      - UWSAPP_DEBUG=off
      - UWSAPP_HOST=${UWSAPP_HOST}
      - UWSAPP_PORT=${UWSAPP_API_PORT}
      - UWSAPP_CLI_HOST=${UWSAPP_HOST}
      - UWSAPP_CLI_SSHPORT=${UWSAPP_CLI_SSHPORT}
    read_only: true
    restart: on-failure
    ports:
      - "127.0.0.1:${UWSAPP_API_PORT}:${UWSAPP_API_PORT}"
    networks:
      - uwsapp-${UWSAPP_ENV}

  uwsweb:
    image: 789470191893.dkr.ecr.us-west-1.amazonaws.com/uws:uwsweb-${UWSAPP_VERSION}
    container_name: uwsweb-${UWSAPP_ENV}-${UWSAPP_VERSION}
    hostname: uwsweb-${UWSAPP_ENV}
    volumes:
      - /srv/uwsapp/${UWSAPP_ENV}/data/web:/var/opt/uwsapp
      - /srv/uwsapp/${UWSAPP_ENV}/run/uwsweb:/run/uwsweb:ro
      - /srv/uwsapp/${UWSAPP_ENV}/run/uwsapi:/run/uwsapi:ro
      - /srv/uwscli/${UWSAPP_ENV}/syslog:/run/uwscli/syslog:ro
    environment:
      - UWSAPP_DEBUG=off
      - UWSAPP_HOST=${UWSAPP_HOST}
      - UWSAPP_PORT=${UWSAPP_WEB_PORT}
      - UWSAPP_API_HOST=${UWSAPP_HOST}
      - UWSAPP_API_CERTFILE=/run/uwsweb/ca/c4bc1cea-8052-54c7-9db8-d25c6b3b747a.pem
      - UWSAPP_API_KEYFILE=/run/uwsweb/ca/c4bc1cea-8052-54c7-9db8-d25c6b3b747a-key.pem
    read_only: true
    restart: on-failure
    ports:
      - "127.0.0.1:${UWSAPP_WEB_PORT}:${UWSAPP_WEB_PORT}"
    networks:
      - uwsapp-${UWSAPP_ENV}
    depends_on:
      - uwsapi

  uwshelp:
    image: 789470191893.dkr.ecr.us-west-1.amazonaws.com/uws:uwshelp-${UWSAPP_VERSION}
    container_name: uwshelp-${UWSAPP_ENV}-${UWSAPP_VERSION}
    hostname: uwshelp-${UWSAPP_ENV}
    volumes:
      - /srv/uwsapp/${UWSAPP_ENV}/data/help:/var/opt/uwsapp
    environment:
      - UWSAPP_DEBUG=off
      - UWSAPP_HOST=${UWSAPP_HOST}
      - UWSAPP_PORT=${UWSAPP_HELP_PORT}
    read_only: true
    restart: on-failure
    ports:
      - "127.0.0.1:${UWSAPP_HELP_PORT}:${UWSAPP_HELP_PORT}"
    networks:
      - uwsapp-${UWSAPP_ENV}

  uwswb:
    image: 789470191893.dkr.ecr.us-west-1.amazonaws.com/uws:uwswb-${UWSAPP_VERSION}
    container_name: uwswb-${UWSAPP_ENV}-${UWSAPP_VERSION}
    hostname: uwswb-${UWSAPP_ENV}
    volumes:
      - /srv/uwsapp/${UWSAPP_ENV}/data/wb:/var/opt/uwsapp
    environment:
      - UWSAPP_DEBUG=off
      - UWSAPP_HOST=${UWSAPP_WB_HOST}
      - UWSAPP_PORT=${UWSAPP_WB_PORT}
    read_only: true
    restart: on-failure
    ports:
      - "127.0.0.1:${UWSAPP_HELP_PORT}:${UWSAPP_HELP_PORT}"
    networks:
      - uwsapp-${UWSAPP_ENV}
