# Copyright (c) Jeremías Casteglione <jeremias@talkingpts.org>
# See LICENSE file.

"""
Django settings for uwsweb project.

Generated by 'django-admin startproject' using Django 3.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

from uwsapp  import config

config.APPNAME = 'web'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config.SECRET_KEY()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config.DEBUG()

ALLOWED_HOSTS = config.ALLOWED_HOSTS()

# Application definition

INSTALLED_APPS = [
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
]

MIDDLEWARE = [
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
	'uwsweb.mw.WebMiddleware',
]

ROOT_URLCONF = 'uwsweb.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [
			BASE_DIR.parent / 'core' / 'templates',
			BASE_DIR.parent / 'web' / 'templates',
		],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
			],
			'string_if_invalid': 'MISS:%s',
		},
	},
]

WSGI_APPLICATION = 'uwsweb.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.sqlite3',
		'NAME': config.DBDIR() / config.DBNAME(),
	}
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{
		'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]

# Auth backends
# https://docs.djangoproject.com/en/3.2/ref/settings/#std-setting-AUTHENTICATION_BACKENDS
AUTHENTICATION_BACKENDS = [
	'django.contrib.auth.backends.ModelBackend',
	'uwsweb.auth.AuthBackend',
]

LOGIN_URL = '/%s' % config.URL('auth/login')
LOGIN_REDIRECT_URL = '/%s' % config.URL('')

SESSION_ENGINE      = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_NAME = config.SESSION_NAME()
SESSION_COOKIE_AGE  = config.SESSION_AGE()

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'
USE_I18N  = False
USE_L10N  = False
USE_TZ    = True

DATE_FORMAT       = 'N j, Y'
DATETIME_FORMAT   = 'r'
TIME_FORMAT       = 'P'
SHORT_DATE_FORMAT = 'Y/m/d'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/%s' % config.URL('static/')
STATICFILES_DIRS = [
	BASE_DIR.parent / 'core' / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'

CSRF_COOKIE_SECURE = True

if not DEBUG and not config.TESTING():
	SECURE_SSL_REDIRECT            = True
	SECURE_HSTS_SECONDS            = 15724800
	SECURE_HSTS_INCLUDE_SUBDOMAINS = True
	SECURE_HSTS_PRELOAD            = True
	SESSION_COOKIE_SECURE          = True
